---
- name: create dir for build files
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_build_dir }}"

- name: copy docker file on host
  copy:
    src: "{{ item }}"
    dest: "{{ docker_build_dir }}/"
  with_items:
    - Dockerfile

- name: copy local.py file for django
  template:
    src: "{{ item }}"
    dest: "{{ docker_build_dir }}/local.py"
  with_items:
    - local.py.j2

- name: build docker django image
  docker_image:
    api_version: "{{ docker_api_version }}"
    path: "{{ docker_build_dir }}"
    name: "{{ docker_django_image_name }}"

- name: check/create docker container
  docker_container:
    docker_api_version: "{{ docker_api_version }}"
    name: "{{ django_container_name }}"
    image: "{{ docker_django_image }}"
    state: started
    restart_policy: always
    exposed_ports: "{{ docker_django_expose }}"
    ports: "{{ docker_django_ports }}"
    memory: "{{ docker_django_memory_limit }}"
