---

- name: Only run apt update_cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Remove old versions of Docker
  apt:
      name: "{{ item }}"
      state: absent
  with_items:
    - docker
    - docker-engine

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
      name: "{{ item }}"
      state: present
      force: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: add apt-key for docker
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: register Debian OS release
  shell: "lsb_release -cs"
  register: release

- name: add repository for docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ release.stdout_lines.0 }} stable"
    state: present
    filename: docker-ce

- name: install Docker package
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
  with_items:
    - docker-ce

- name: Install python pip
  apt:
      name: "{{ item }}"
      state: present
      force: yes
  with_items:
    - python
    - python-pip

- name: install docker-py
  pip:
    name: docker-py
  ignore_errors: yes

