---
- name: check/create host data dir
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_postgres_host_data_dir }}"


- name: check/create postgresql container
  docker_container:
    docker_api_version: "{{ docker_api_version }}"
    name: "{{ postgres_container_name }}"
    image: "{{ docker_postgres_image }}"
    state: started
    restart_policy: always
    exposed_ports: "{{ docker_postgres_expose }}"
    ports: "{{ docker_postgres_ports }}"
    volumes: "{{ docker_postgres_directory_volumes }}"
    memory: "{{ docker_postgres_memory_limit }}"
    env: "{{ docker_postgres_env }}"

- name: inspect postgres docker
  command: >
    docker inspect --type=container
    --format='{''{ .NetworkSettings.IPAddress }''}'
    {{ postgres_container_name }}
  register: postgres_address_result

- set_fact: postgres_container_address={{ postgres_address_result.stdout }}
